### ISSUE TITLE
Kick off an MVP for the to-do-app

### ISSUE THREAD

**Issue by Danswar** [OM33/to-do-app#1]
As a Product Owner, I request the development of a To-Do List Management Application that can be used to efficiently manage daily tasks and activities.

In this first iteration we want to have in place the main components of the UI and the more basic functionality. The styling of the application is up to the developer assigned to the task but I strongly suggest following a layout like this:

<img width="538" alt="Screenshot 2023-02-08 at 11 20 11" src="https://user-images.githubusercontent.com/48102227/217555806-667bfdb7-aaa9-4d15-a657-95eeb8a8393e.png">

It is also required to use the following packages:
- create-react-app
- Material-UI

The deliverable for this task is the application deployed in a free hosting, it is up to developer to choose which one to use.

Add any question to the issue and I will be answering as soon as possible. Thank you very much.

**Comment by OM33** [comment]
Hi, sorry for late reply, I sent my progress through master branch. 
I will continue sending my progress along the day

**Comment by Danswar** [comment]
Hey Olga thanks for the updates, the code looks amazing, well done! Can I ask you for deployed version of the app please? it would be nice see it working as it is now.

In addition to that, it would be great if you could create [Pull Requests](https://docs.github.com/en/pull-requests) for any further changes, that way we can both agree about any new features and you can get [Code Reviews](https://www.atlassian.com/agile/software-development/code-reviews) from other engineers before your code goes to production.

It is also desirable to maintain a naming convention for the branches that we use for new features. To better map branches to their business context and to follow the most common practices, we can do the following pattern:

**[number of the issue in Github]-[short descriptor]**

This way the name of branch for this particular issue would be something like: **1-MVP-to-app-init**.

That was an amazing progress, thanks for that I'm looking forward to see it in action.

**Comment by OM33** [comment]
Hi I finished the first version for the project.
I await for further requirements or recommendations to do 
You are able to see the deployed project at this link: https://todo-app-om33.netlify.app/
