### ISSUE TITLE
Connect the application to the To-Do API

### ISSUE THREAD

**Issue by Danswar** [OM33/to-do-app#3]
We want to connect our application to the To Do API provided by [https://jsonplaceholder.typicode.com](https://jsonplaceholder.typicode.com)

The new workflow should be something like this:
- When the app starts, fetch the to-dos from the api.
- While the app is fetching the to-dos, display a spinner or any other loading element on the list.
- After fetching, clean the loading element and display 10 to-dos from the API.
- To-dos inputed by the user should be added to the list.

Please let me know if you have any questions or more details are required.

**Comment by OM33** [comment]
Hi, good morning, hope you were fine, I finished all the requirements. I proceed to pull request.
