### ISSUE TITLE
Readme improvements

### ISSUE THREAD

**Issue by Danswar** [OM33/to-do-app#5]
Currently our Readme looks kind of generic, we might want to fill it up with more useful information like:

- A brief summary of what the application does (optionally a screenshot).
- A link to our deployed version.
- How to start the application.
- Instructions on how to deploy it (brief explanation).
- Any other that you consider important and prone to forget.

Also remove all unnecessary boilerplate from it.

<img width="1156" alt="Screenshot 2023-02-28 at 16 34 57" src="https://user-images.githubusercontent.com/48102227/221959923-f07ff8db-b19d-4ed1-a851-aaadeb4fd235.png">

**Comment by OM33** [comment]
Hi, You are right, I made a few changes and put some screenshots from Netlify deployed version. 
Please kindly check it and tell me what do you think

**Comment by Danswar** [comment]
Excellent, thanks Olga!

A quick suggestion: next time it would be better to have a PR before changing `master`.

Closing this ticket as it is completed.

**Comment by OM33** [comment]
Ok, thak you for your suggestion, I will take that in count next time
